FROM node:14-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm i 

# Bundle app source
COPY . .


# Expose port and start command
EXPOSE 5000
CMD ["node", "index"]